apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-pipeline
  namespace: swampup-cicd
spec:
  params:
    - description: The docker image to deploy
      name: DOCKER_TAG
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'git@github.com:philipfoster/SwampUP23_Demo_Deployment_Files.git'
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: manifests
        - name: ssh-directory
          workspace: git-ssh
    - name: update-dev-manifest
      params:
        - name: SCRIPT
          value: >-
            yq -i e ".images[0].newTag |=\"$(params.DOCKER_TAG)\""
            overlays/dev/kustomization.yml
        - name: image
          value: >-
            docker.io/mikefarah/yq:4.27.5@sha256:2be3626ed633fbe1fc33ee9343a1256a6be53334412b2251b9a859f8c145bb53
        - name: files
          value: []
        - name: expression
          value: ''
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: yq
      workspaces:
        - name: source
          workspace: manifests
    - name: deploy
      params:
        - name: BASE_IMAGE
          value: >-
            cgr.dev/chainguard/git:root-2.39@sha256:7759f87050dd8bacabe61354d75ccd7f864d6b6f8ec42697db7159eccd491139
        - name: GIT_USER_NAME
          value: 'Tekton CICD'
        - name: GIT_USER_EMAIL
          value: 'swampup23.demo@nvsconsulting.io'
        - name: GIT_SCRIPT
          value: |-
            git config --global --add safe.directory /workspace/source && \
            git checkout main && \
            git add --all && \
            git commit -m "Bump release version to $(params.DOCKER_TAG)" && \
            eval `ssh-agent -s` && \
            ssh-add ~/.ssh/id_rsa && \
            git push -u origin main
        - name: USER_HOME
          value: /root
        - name: VERBOSE
          value: 'true'
      runAfter:
        - update-dev-manifest
      taskRef:
        kind: ClusterTask
        name: git-cli
      workspaces:
        - name: source
          workspace: manifests
        - name: ssh-directory
          workspace: git-ssh
  workspaces:
    - name: manifests
    - name: git-ssh
