apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swampup23-demo-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: swampup-dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: overlays/dev
    repoURL: 'git@github.com:philipfoster/SwampUP23_Demo_Deployment_Files.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true