apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swampup24-demo-test
  namespace: openshift-gitops
spec:
  destination:
    namespace: swampup-test
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: overlays/test
    repoURL: 'git@github.com:JairoLedezma/SwampUP24_Demo_Deployment_Files.gitt'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true